# Generated by Django 3.2.9 on 2021-11-29 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comments_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='uer',
        ),
    ]
