# Generated by Django 3.2.9 on 2021-11-29 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20211129_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcomment',
            old_name='uer',
            new_name='user',
        ),
    ]
